apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['backend-service.ecommerce.svc.cluster.local:4000']

      - job_name: 'mongo'
        static_configs:
          - targets: ['mongo-service.ecommerce.svc.cluster.local:27017']

      - job_name: 'notification'
        static_configs:
          - targets: ['notification-service.ecommerce.svc.cluster.local:5001']
