version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "4000:4000"
    environment:
      - MongoDBUrl=mongodb://mongo:27017/care
      - PORT=4000
      - JWT_SECRET=secretkey123
    depends_on:
      - mongo

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000

  notification:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NOTIFY_KEY=test123
    depends_on:
      - backend

volumes:
  mongo_data:
