apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ecommerce-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: MongoDBUrl
              value: "mongodb://mongo-service:27017/care"
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              value: "secretkey123"
