apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
