apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: ecommerce-notification:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: MAIL_USER
              value: "your_email@gmail.com"
            - name: MAIL_PASS
              value: "your_app_password"
